export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const ADD_USER = 'ADD_USER';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const CANCEL_EDIT_USER = 'CANCEL_EDIT_USER';
export const BACK_TO_USERSLIST = 'BACK_TO_USERSLIST';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const ADD_USER_TO_UNIVERSITY = 'ADD_USER_TO_UNIVERSITY';
export const GET_UNIVERSITIES_SUCCESS = 'GET_UNIVERSITIES_SUCCESS';
export const BACK_TO_UNIVERSITIESLIST = 'BACK_TO_UNIVERSITIESLIST';
export const ADD_USER_TO_UNIVERSITY_SUCCESS = 'ADD_USER_TO_UNIVERSITY_SUCCESS';
export const GET_USERS = 'GET_USERS';



